version: '3'
services:
  backend:
    container_name: subconverter
    image: tindy2013/subconverter:latest
    restart: unless-stopped
    ports:
      - "25500:25500"
  frontend:
    container_name: subweb
    image: mkdir700/sub-web:latest
    restart: unless-stopped
    ports:
      - "58080:80"
    env_file:
      - ./conf/.env
